Repository ZJUVAG/NetV.js, pull requests merged in 2020-09, with the labels that each got.

#58 fix: 🐛 transformGraphPosition (mid position)
  src/utils/utils.ts
Labels: bugfix

#59 Label
  examples/miserables-label/index.html
  examples/miserables-label/index.js
  src/configs.ts
  src/index.ts
  src/interaction/interaction.ts
  src/interfaces.ts
  src/label/label.ts
  src/node.ts
  src/renderer/elements/link/render-link.ts
  src/renderer/elements/node/render-node.ts
  src/renderer/index.ts
  src/renderer/interfaces.ts
Labels: enhancement

#60 Interaction: drag node support
  src/index.ts
  src/interaction/interaction.ts
  src/link.ts
  src/node.ts
Labels: bugfix, enhancement

#67 Lazy link update
  benchmarks/index.html
  benchmarks/index.js
  benchmarks/lib/stats.min.js
  benchmarks/lib/utils.js
  src/configs.ts
  src/index.ts
  src/interaction/interaction.ts
  src/interfaces.ts
  src/node.ts
  src/renderer/elements/link/render-link.ts
  src/renderer/index.ts
Labels: bugfix
